DATA_DIR: ./data/tfrecord
LOG_DIR: ./logs
OUTPUTS: ./outputs
INPUT_HEIGHT: 256
INPUT_WIDTH: 256
N_CHANNEL: 3
SOLVER:
  EPOCHS: 200
  INIT_LR: 0.0001
  MOMENTUM: 0.9
  LR_SCHEDULE: cosine
  OPTIMS: sgd
  TRAINING: True
  REGULARIZATION: 0.0001
  BATCH_SIZE: 48